from __future__ import annotations

from enum import Enum


class SearchErrorCode(str, Enum):
    KB_NOT_READY = "SEARCH_KB_NOT_READY"
    QUERY_EMBEDDING_FAILED = "SEARCH_QUERY_EMBEDDING_FAILED"
    QUERY_EMBEDDING_DIMENSION_MISMATCH = "QUERY_EMBEDDING_DIMENSION_MISMATCH"
    QDRANT_FAILED = "SEARCH_QDRANT_FAILED"
    NO_RESULTS = "SEARCH_NO_RESULTS"
    CONTEXT_EMPTY = "SEARCH_CONTEXT_EMPTY"
    CITATION_BUILD_FAILED = "SEARCH_CITATION_BUILD_FAILED"
    PERMISSION_DENIED = "SEARCH_PERMISSION_DENIED"
    KB_NOT_FOUND = "SEARCH_KB_NOT_FOUND"
    TENANT_SCOPE_MISMATCH = "SEARCH_TENANT_SCOPE_MISMATCH"


__all__ = ["SearchErrorCode"]
