# backend/shared/text/language_lexicon.py
# Feladat: Többnyelvű, szabályalapú text lexikont tartalmaz hu/en/es nyelvekre és generic fallbackre. Kérdésszavakat, stopwordöket, idő- és helyjelölőket, állapot- és relációmarkereket ad a query, claim és chat feldolgozó rétegeknek. Shared lexikon utility, amely nem kötődik konkrét app domain modellhez.
# Sárközi Mihály - 2026.05.21

from __future__ import annotations

from collections import OrderedDict
import unicodedata

SUPPORTED_LEXICON_LANGUAGES: tuple[str, ...] = ("hu", "en", "es")
DEFAULT_LEXICON_LANGUAGE = "en"
_GENERIC_LEXICON_LANGUAGE = "generic"

_LEXICON_DATA: dict[str, dict[str, tuple[str, ...]]] = {
    _GENERIC_LEXICON_LANGUAGE: {
        "question_words": ("what", "which", "who", "where", "when", "why", "how"),
        "helper_verbs": ("is", "are", "was", "were", "do", "does", "did"),
        "entity_stopwords": (
            "what",
            "which",
            "who",
            "where",
            "when",
            "why",
            "how",
            "is",
            "are",
            "was",
            "were",
            "do",
            "does",
            "did",
        ),
        "question_stopwords": (
            "what",
            "which",
            "who",
            "where",
            "when",
            "why",
            "how",
            "is",
            "are",
            "was",
            "were",
            "do",
            "does",
            "did",
            "and",
            "or",
            "the",
            "a",
            "an",
        ),
        "entity_hint_stopwords": ("status", "state", "time", "place"),
        "descriptor_terms": ("number", "identifier", "address", "email", "phone", "date"),
        "entity_suffixes": (),
        "name_suffixes": (),
        "place_suffixes": (),
        "time_months": (
            "january",
            "february",
            "march",
            "april",
            "may",
            "june",
            "july",
            "august",
            "september",
            "october",
            "november",
            "december",
        ),
        "time_weekdays": (
            "monday",
            "tuesday",
            "wednesday",
            "thursday",
            "friday",
            "saturday",
            "sunday",
        ),
        "time_relative_current": ("today", "currently", "now"),
        "time_relative_open": ("since",),
        "time_relative_bounded": ("before", "after", "previously", "earlier"),
        "time_event_markers": ("created", "updated", "changed", "completed"),
        "location_qualifiers": ("office", "branch", "center", "site", "location", "city", "country"),
        "state_markers": ("status", "active", "inactive"),
        "relation_markers": ("use", "uses", "using", "integrate", "integrates", "integrated"),
        "rule_markers": ("must", "should", "required", "rule", "policy"),
        "event_markers": ("created", "updated", "completed", "happened", "changed", "deprecated"),
        "descriptor_markers": ("who is", "what is", "describe", "description", "lead", "responsible", "apply", "applies"),
        "historical_markers": ("was", "were", "previously", "historical", "in 20", "in 19"),
        "current_markers": ("current", "currently", "active now"),
        "answer_type_location_words": ("where",),
        "answer_type_time_words": ("when",),
        "answer_type_person_words": ("who",),
        "answer_type_explanation_words": ("why",),
        "answer_type_object_words": ("what",),
    },
    "hu": {
        "question_words": ("mi", "mit", "milyen", "ki", "kik", "hol", "mikor", "hogyan", "mennyi", "melyik", "miert", "miért"),
        "helper_verbs": ("van", "volt", "lesz", "lenni", "tud", "tudsz", "tudja", "tudtok", "tudunk"),
        "entity_stopwords": (
            "a",
            "az",
            "egy",
            "de",
            "es",
            "és",
            "vagy",
            "hogy",
            "milyen",
            "mit",
            "mi",
            "ki",
            "kik",
            "hol",
            "mikor",
            "hogyan",
            "tud",
            "tudsz",
            "tudja",
            "tudtok",
            "tudunk",
            "program",
            "programot",
            "keszitett",
            "készített",
            "van",
            "volt",
            "lesz",
            "lenni",
        ),
        "question_stopwords": (
            "ki",
            "kik",
            "mi",
            "mit",
            "de",
            "mikor",
            "hol",
            "hogyan",
            "milyen",
            "mennyi",
            "melyik",
            "tud",
            "tudsz",
            "tudja",
            "tudtok",
            "tudunk",
            "van",
            "volt",
            "lesz",
            "egy",
            "az",
            "a",
            "és",
            "vagy",
            "meg",
            "hogy",
            "akkor",
        ),
        "entity_hint_stopwords": ("szem", "szeme", "szin", "szine", "allapot", "statusz", "hely", "ido"),
        "descriptor_terms": ("szam", "szama", "szamu", "azonosito", "igazolvany", "utlevel", "telefonszam", "email", "cim", "datum"),
        "entity_suffixes": (
            "akkal",
            "ekkel",
            "okkal",
            "akkel",
            "akal",
            "ekel",
            "nek",
            "nak",
            "val",
            "vel",
            "rol",
            "ról",
            "tol",
            "tól",
            "bol",
            "ból",
            "ben",
            "ban",
            "hoz",
            "hez",
            "höz",
            "ra",
            "re",
            "on",
            "en",
            "ön",
            "ot",
            "et",
            "at",
            "t",
        ),
        "name_suffixes": (
            "nek",
            "nak",
            "val",
            "vel",
            "rol",
            "ról",
            "tol",
            "tól",
            "bol",
            "ból",
            "ban",
            "ben",
            "hoz",
            "hez",
            "höz",
            "ra",
            "re",
            "on",
            "en",
            "ön",
            "nal",
            "nál",
            "nel",
            "nél",
            "ot",
            "et",
            "at",
            "t",
        ),
        "place_suffixes": ("ban", "ben", "on", "en", "ön", "ba", "be", "ra", "re", "nál", "nél", "ból", "ből", "hoz", "hez", "höz"),
        "time_months": (
            "január",
            "február",
            "március",
            "április",
            "május",
            "június",
            "július",
            "augusztus",
            "szeptember",
            "október",
            "november",
            "december",
            "januar",
            "februar",
            "marcius",
            "aprilis",
            "majus",
            "junius",
            "julius",
            "oktober",
        ),
        "time_weekdays": (
            "hétfő",
            "kedd",
            "szerda",
            "csütörtök",
            "péntek",
            "szombat",
            "vasárnap",
            "hetfo",
            "csutortok",
            "pentek",
            "vasarnap",
        ),
        "time_relative_current": ("ma", "jelenleg", "most"),
        "time_relative_open": ("óta", "ota"),
        "time_relative_bounded": ("előtt", "elott", "után", "utan", "korábban", "korabban"),
        "time_event_markers": ("létrejött", "módosult", "frissült", "megszűnt"),
        "location_qualifiers": (
            "iroda",
            "irodák",
            "telephely",
            "helyszín",
            "helyszin",
            "város",
            "varos",
            "ország",
            "orszag",
            "budapesti",
            "londoni",
            "madridi",
            "berlini",
        ),
        "state_markers": ("statusz", "állapot", "allapot", "aktív", "aktiv", "inaktív", "inaktiv"),
        "relation_markers": ("használ", "hasznal", "kezeli", "kapcsolódik", "kapcsolodik", "függ", "fugg"),
        "rule_markers": ("kell", "kötelező", "kotelezo", "szabály", "szabaly", "szabályzat", "szabalyzat"),
        "event_markers": ("létrejött", "letrejott", "módosult", "modosult", "frissült", "frissult", "megszűnt", "megszunt"),
        "descriptor_markers": ("ki", "mi", "milyen", "leírás", "leiras", "felelős", "felelos"),
        "historical_markers": ("korábban", "korabban", "volt", "in 20", "in 19"),
        "current_markers": ("jelenleg", "most"),
        "answer_type_location_words": ("hol",),
        "answer_type_time_words": ("mikor",),
        "answer_type_person_words": ("ki", "kik"),
        "answer_type_explanation_words": ("miért", "miert"),
        "answer_type_object_words": ("mit", "mi"),
    },
    "en": {
        "question_words": ("what", "which", "who", "where", "when", "why", "how"),
        "helper_verbs": ("is", "are", "was", "were", "do", "does", "did"),
        "entity_stopwords": ("the", "a", "an", "and", "or", "what", "which", "who", "where", "when", "why", "how", "is", "are", "was", "were"),
        "question_stopwords": ("the", "a", "an", "and", "or", "what", "which", "who", "where", "when", "why", "how", "is", "are", "was", "were"),
        "entity_hint_stopwords": ("eye", "state", "status", "place", "time"),
        "descriptor_terms": ("number", "identifier", "id", "passport", "phone", "email", "address", "date"),
        "entity_suffixes": ("'s",),
        "name_suffixes": ("'s",),
        "place_suffixes": (),
        "time_months": (
            "january",
            "february",
            "march",
            "april",
            "may",
            "june",
            "july",
            "august",
            "september",
            "october",
            "november",
            "december",
        ),
        "time_weekdays": ("monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"),
        "time_relative_current": ("today", "currently", "now"),
        "time_relative_open": ("since",),
        "time_relative_bounded": ("before", "after", "earlier", "previously"),
        "time_event_markers": ("created", "updated", "changed", "completed", "deprecated"),
        "location_qualifiers": ("office", "offices", "branch", "branches", "center", "centers", "site", "sites", "location"),
        "state_markers": ("status", "active", "inactive"),
        "relation_markers": ("use", "uses", "using", "integrate", "integrates", "integrated"),
        "rule_markers": ("must", "should", "required", "rule", "policy"),
        "event_markers": ("created", "updated", "completed", "happened", "deprecated", "changed", "launched"),
        "descriptor_markers": ("who is", "what is", "describe", "description", "lead", "responsible", "apply", "applies"),
        "historical_markers": ("was", "were", "previously", "historical", "in 20", "in 19"),
        "current_markers": ("current", "currently", "active now"),
        "answer_type_location_words": ("where",),
        "answer_type_time_words": ("when",),
        "answer_type_person_words": ("who",),
        "answer_type_explanation_words": ("why",),
        "answer_type_object_words": ("what",),
    },
    "es": {
        "question_words": ("que", "qué", "quien", "quién", "donde", "dónde", "cuando", "cuándo", "como", "cómo"),
        "helper_verbs": ("es", "son", "fue", "era", "debe", "debería", "deberia", "puede"),
        "entity_stopwords": ("el", "la", "los", "las", "un", "una", "y", "o", "de", "del", "en", "es", "fue", "que", "qué", "quien", "quién"),
        "question_stopwords": ("el", "la", "los", "las", "un", "una", "y", "o", "de", "del", "en", "es", "fue", "que", "qué", "quien", "quién"),
        "entity_hint_stopwords": ("estado", "tiempo", "lugar"),
        "descriptor_terms": ("numero", "número", "identificador", "pasaporte", "telefono", "teléfono", "correo", "direccion", "dirección", "fecha"),
        "entity_suffixes": (),
        "name_suffixes": (),
        "place_suffixes": (),
        "time_months": (
            "enero",
            "febrero",
            "marzo",
            "abril",
            "mayo",
            "junio",
            "julio",
            "agosto",
            "septiembre",
            "octubre",
            "noviembre",
            "diciembre",
        ),
        "time_weekdays": ("lunes", "martes", "miércoles", "miercoles", "jueves", "viernes", "sábado", "sabado", "domingo"),
        "time_relative_current": ("hoy", "actualmente", "ahora"),
        "time_relative_open": ("desde",),
        "time_relative_bounded": ("antes", "después", "despues", "anteriormente"),
        "time_event_markers": ("creado", "creada", "actualizado", "actualizada"),
        "location_qualifiers": ("oficina", "ubicación", "ubicacion", "sede", "sitio", "ciudad", "país", "pais"),
        "state_markers": ("estado", "activo", "activa", "inactivo", "inactiva"),
        "relation_markers": ("utiliza", "usa", "conecta", "depende", "integra"),
        "rule_markers": ("debe", "debería", "deberia", "obligatorio", "prohibido", "política", "politica"),
        "event_markers": ("creado", "creada", "actualizado", "actualizada", "ocurrió", "ocurrio"),
        "descriptor_markers": ("quien es", "quién es", "que es", "qué es", "describe", "responsable", "aplica"),
        "historical_markers": ("fue", "era", "anteriormente", "en 20", "en 19"),
        "current_markers": ("actualmente", "ahora"),
        "answer_type_location_words": ("donde", "dónde"),
        "answer_type_time_words": ("cuando", "cuándo"),
        "answer_type_person_words": ("quien", "quién"),
        "answer_type_explanation_words": ("porque", "por qué", "porqué"),
        "answer_type_object_words": ("que", "qué"),
    },
}

_REQUIRED_LEXICON_KEYS: tuple[str, ...] = (
    "question_words",
    "helper_verbs",
    "entity_stopwords",
    "question_stopwords",
    "descriptor_terms",
    "entity_suffixes",
    "name_suffixes",
    "place_suffixes",
    "time_months",
    "time_weekdays",
    "time_relative_current",
    "time_relative_open",
    "time_relative_bounded",
    "time_event_markers",
)

_MONTH_INDEX_BY_LANGUAGE: dict[str, dict[str, int]] = {
    "hu": {
        "januar": 1,
        "februar": 2,
        "marcius": 3,
        "aprilis": 4,
        "majus": 5,
        "junius": 6,
        "julius": 7,
        "augusztus": 8,
        "szeptember": 9,
        "oktober": 10,
        "november": 11,
        "december": 12,
    },
    "en": {
        "january": 1,
        "february": 2,
        "march": 3,
        "april": 4,
        "may": 5,
        "june": 6,
        "july": 7,
        "august": 8,
        "september": 9,
        "october": 10,
        "november": 11,
        "december": 12,
    },
    "es": {
        "enero": 1,
        "febrero": 2,
        "marzo": 3,
        "abril": 4,
        "mayo": 5,
        "junio": 6,
        "julio": 7,
        "agosto": 8,
        "septiembre": 9,
        "octubre": 10,
        "noviembre": 11,
        "diciembre": 12,
    },
}


def normalize_lexicon_language(language: str | None) -> str:
    normalized = str(language or "").strip().lower().split("-")[0]
    if normalized in SUPPORTED_LEXICON_LANGUAGES:
        return normalized
    return DEFAULT_LEXICON_LANGUAGE


def _fallback_chain(language: str | None) -> tuple[str, ...]:
    normalized = normalize_lexicon_language(language)
    if normalized == DEFAULT_LEXICON_LANGUAGE:
        return (normalized, _GENERIC_LEXICON_LANGUAGE)
    return (normalized, DEFAULT_LEXICON_LANGUAGE, _GENERIC_LEXICON_LANGUAGE)


def get_lexicon_terms(language: str | None, key: str, *, include_fallback: bool = True) -> tuple[str, ...]:
    values: "OrderedDict[str, None]" = OrderedDict()
    language_codes = _fallback_chain(language) if include_fallback else (normalize_lexicon_language(language),)
    for language_code in language_codes:
        for item in _LEXICON_DATA.get(language_code, {}).get(key, ()):
            token = str(item or "").strip()
            if token:
                values[token] = None
    return tuple(values.keys())


def validate_language_lexicon() -> dict[str, tuple[str, ...]]:
    errors: dict[str, tuple[str, ...]] = {}
    for language in SUPPORTED_LEXICON_LANGUAGES:
        data = _LEXICON_DATA.get(language, {})
        missing = [key for key in _REQUIRED_LEXICON_KEYS if key not in data]
        if missing:
            errors[language] = tuple(missing)
    return errors


def get_month_number(language: str | None, month_text: str | None) -> int | None:
    normalized_language = normalize_lexicon_language(language)
    normalized = unicodedata.normalize("NFKD", str(month_text or "").strip().lower())
    folded = "".join(char for char in normalized if not unicodedata.combining(char))
    if not folded:
        return None
    return _MONTH_INDEX_BY_LANGUAGE.get(normalized_language, {}).get(folded)


__all__ = [
    "DEFAULT_LEXICON_LANGUAGE",
    "SUPPORTED_LEXICON_LANGUAGES",
    "get_lexicon_terms",
    "get_month_number",
    "normalize_lexicon_language",
    "validate_language_lexicon",
]
