from __future__ import annotations

from enum import Enum


class EmbeddingErrorCode(str, Enum):
    DISCOVERY_JOB_NOT_FOUND = "DISCOVERY_JOB_NOT_FOUND"
    DISCOVERY_NOT_READY = "DISCOVERY_NOT_READY"
    JOB_ALREADY_RUNNING = "JOB_ALREADY_RUNNING"
    NO_CHUNKS_FOR_EMBEDDING = "NO_CHUNKS_FOR_EMBEDDING"
    MISSING_EMBEDDING = "MISSING_EMBEDDING"
    EMBEDDING_DIMENSION_MISMATCH = "EMBEDDING_DIMENSION_MISMATCH"
    EMPTY_EMBEDDING_VECTOR = "EMPTY_EMBEDDING_VECTOR"
    EMBEDDING_PROVIDER_FAILED = "EMBEDDING_PROVIDER_FAILED"
    EMBEDDING_PARTIAL_FAILURE = "EMBEDDING_PARTIAL_FAILURE"
    LOCAL_EMBEDDING_MODEL_LOAD_FAILED = "LOCAL_EMBEDDING_MODEL_LOAD_FAILED"
    LOCAL_EMBEDDING_GENERATION_FAILED = "LOCAL_EMBEDDING_GENERATION_FAILED"
    LOCAL_EMBEDDING_DIMENSION_MISMATCH = "LOCAL_EMBEDDING_DIMENSION_MISMATCH"
    INTERNAL_ERROR = "INTERNAL_ERROR"


__all__ = ["EmbeddingErrorCode"]
